// Valid S3 Requests
// https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations_Amazon_Simple_Storage_Service.html
//
// Removed:
// - GetBucketLifecycle
// - GetBucketNotification
// - ListDirectoryBuckets
// - PutBucketLifecycle
// - PutBucketNotification
//
// Added:
// - OptionsPreflight
// - PostObject
#[derive(Default, Debug, Clone, PartialEq)]
pub enum S3Action {
    #[default]
    Unknown,
    AbortMultipartUpload,
    CompleteMultipartUpload,
    CopyObject,
    CreateBucket,
    CreateMultipartUpload,
    CreateSession,
    DeleteBucket,
    DeleteBucketAnalyticsConfiguration,
    DeleteBucketCors,
    DeleteBucketEncryption,
    DeleteBucketIntelligentTieringConfiguration,
    DeleteBucketInventoryConfiguration,
    DeleteBucketLifecycle,
    DeleteBucketMetricsConfiguration,
    DeleteBucketOwnershipControls,
    DeleteBucketPolicy,
    DeleteBucketReplication,
    DeleteBucketTagging,
    DeleteBucketWebsite,
    DeleteObject,
    DeleteObjects,
    DeleteObjectTagging,
    DeletePublicAccessBlock,
    GetBucketAccelerateConfiguration,
    GetBucketAcl,
    GetBucketAnalyticsConfiguration,
    GetBucketCors,
    GetBucketEncryption,
    GetBucketIntelligentTieringConfiguration,
    GetBucketInventoryConfiguration,
    GetBucketLifecycleConfiguration,
    GetBucketLocation,
    GetBucketLogging,
    GetBucketMetricsConfiguration,
    GetBucketNotificationConfiguration,
    GetBucketOwnershipControls,
    GetBucketPolicy,
    GetBucketPolicyStatus,
    GetBucketReplication,
    GetBucketRequestPayment,
    GetBucketTagging,
    GetBucketVersioning,
    GetBucketWebsite,
    GetObject,
    GetObjectAcl,
    GetObjectAttributes,
    GetObjectLegalHold,
    GetObjectLockConfiguration,
    GetObjectRetention,
    GetObjectTagging,
    GetObjectTorrent,
    GetPublicAccessBlock,
    HeadBucket,
    HeadObject,
    ListBucketAnalyticsConfigurations,
    ListBucketIntelligentTieringConfigurations,
    ListBucketInventoryConfigurations,
    ListBucketMetricsConfigurations,
    ListBuckets,
    ListMultipartUploads,
    ListObjects,
    ListObjectsV2,
    ListObjectVersions,
    ListParts,
    OptionsPreflight,
    PostObject,
    PutBucketAccelerateConfiguration,
    PutBucketAcl,
    PutBucketAnalyticsConfiguration,
    PutBucketCors,
    PutBucketEncryption,
    PutBucketIntelligentTieringConfiguration,
    PutBucketInventoryConfiguration,
    PutBucketLifecycleConfiguration,
    PutBucketLogging,
    PutBucketMetricsConfiguration,
    PutBucketNotificationConfiguration,
    PutBucketOwnershipControls,
    PutBucketPolicy,
    PutBucketReplication,
    PutBucketRequestPayment,
    PutBucketTagging,
    PutBucketVersioning,
    PutBucketWebsite,
    PutObject,
    PutObjectAcl,
    PutObjectLegalHold,
    PutObjectLockConfiguration,
    PutObjectRetention,
    PutObjectTagging,
    PutPublicAccessBlock,
    RestoreObject,
    SelectObjectContent,
    UploadPart,
    UploadPartCopy,
    WriteGetObjectResponse,
}
